[package]
name = "artificial-intelligence-turtorial-rust"
version = "0.1.0"
authors = ["Juyoung35 <68434709+Juyoung35@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
